version: '3'

services:
    customers-service:
        image: nexus-ci.kumuluz.com/customers
        restart: always
        ports:
            - 8083:8080
        networks:
            - customers-service-network

    customers-database:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=dbuser
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=customer
        ports:
            - 5432:5432
        networks:
            - customers-service-network

networks:
  customers-service-network: