kumuluzee:
  name: kubernetes-customers
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:postgresql://customers-database:5433/customer
      username: dbuser
      password: postgres
      max-pool-size: 20
  cors-filter:
    servlet:
      allow-origin: "*"
rest-properties:
  external-services:
    order-service:
      enabled: false
